version: '3.8'

services:
  fauna:
    image: fauna/faunadb
    ports:
      - 8443:8443
      - 8084:8084
    volumes:
      - fauna_data:/var/lib/faunadb
  redis:
    image: redis
    command: redis-server --requirepass myredispassword
    ports:
      - 6379:6379

volumes:
  fauna_data:
    driver: local
