version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: chatskee_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGTZ: utc
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8080:8080'
    volumes:
      - ./hasura/migrations:/hasura-migrations
    depends_on:
      - 'postgres'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:root@postgres:5432/chatskee_db
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES:
        startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
      # NOTE: this is the ip assigned to the pc running this
      # run 'ifconfig' to get it, we need this because this runs
      # inside docker and the next app runs outside.
      ACTION_BASE_URL: http://172.25.54.224:3000
volumes:
  postgres_data:
