name: Hasura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hasura
        uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          PATH_TO_HASURA_PROJECT_ROOT: ./hasura
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_MIGRATIONS_ENABLED: true
